python main.py \
       --b 128 \
       --gridheight 16 \
       --gridwidth 16 \
       --testgrid '/media/user/HDD1/DATASET/CUEING-D/testing/grid.txt' \
       --testgazemaps '/media/user/HDD1/DATASET/CUEING-D/testing/gazemap_images' \
       --testdir '/media/user/HDD1/DATASET/CUEING-D/testing/camera_images' \
       --yolo5bbtest '/media/user/HDD1/DATASET/CUEING-D/testing/bbox' \
       --weight 'weight/BDD-A'\
       --gpu 0 \
       --visualizations \
       --no_train
